hotsite/hotsite/core/urls.py
from django.conf.urls import url

from hotsite.panel.views import login
from hotsite.posts.views import post, category
from .views import *

urlpatterns = [
    url('^$', index, name='index'),
    url('^login/$', login, name='login'),

    url('^catalog/$', catalog, name='catalog'),

    url('^vulnerability/(?P<pk>\w+)/$', vulnerability, name="vulnerability"),

    url('^providers/$', providers, name="providers"),
    url('^provider/(?P<pk>\w+)/$', provider, name="provider"),

    url('^products/$', products, name="products"),
    url('^product/(?P<pk>\w+)/$', product, name="product"),

    url('^category/(?P<category_slug>[\w-]+)/', category, name="category"),
    url('^article/(?P<category_slug>[\w-]+)/(?P<post_slug>[\w-]+)/', post, name="post"),
]

hotsite/hotsite/panel/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [

    url('^login/$', login, name='login'),
    url('^logout/$', logout, name='logout'),

    url('^catalog/', include('hotsite.catalog.urls', namespace='catalog')),

    url('^posts/', include('hotsite.posts.urls', namespace='posts')),

    url('^$', index, name='index'),
]

hotsite/hotsite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url('^', include('hotsite.core.urls', namespace='core')),
    url('^panel/', include('hotsite.panel.urls', namespace='panel')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotsite/hotsite/catalog/models.py
from django.db import models
from django.contrib.auth.models import User


class Provider(models.Model):
    name = models.TextField(verbose_name='Nome')

    class Meta:
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.TextField(verbose_name='Nome')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class License(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nome')

    class Meta:
        verbose_name = 'Licença'
        verbose_name_plural = 'Licenças'

    def __str__(self):
        return self.name


class TypeUse(models.Model):
    name = models.CharField(max_length=25, verbose_name='Nome')

    class Meta:
        verbose_name = 'Tipo de uso'
        verbose_name_plural = 'Tipo de uso'

    def __str__(self):
        return self.name


class Software(models.Model):
    name = models.TextField(verbose_name='Nome')
    process_number = models.TextField(null=True, blank=True, verbose_name='Número do processo')
    version_stable = models.CharField(max_length=15, default='-', verbose_name='Versão estável')
    licenses_number = models.CharField(max_length=25, default='-', verbose_name='Número de licenças')
    note = models.TextField(verbose_name='Observações')

    license = models.ForeignKey(License, default=1, verbose_name=License._meta.verbose_name)
    type = models.ForeignKey(TypeUse, null=True, blank=True, verbose_name=TypeUse._meta.verbose_name)
    provider = models.ForeignKey(Provider, verbose_name=Provider._meta.verbose_name)
    category = models.ForeignKey(Category, verbose_name=Category._meta.verbose_name)

    def __str__(self):
        return self.name


class Vulnerability(models.Model):
    SEVERITY_CHOICES = (
        ('Cuidado', 'Cuidado'),
        ('Alto', 'Alto'),
        ('Crítico', 'Crítico')
    )

    name = models.TextField(verbose_name='Nome')
    description = models.TextField(null=True, blank=True, verbose_name='Descrição')
    solution = models.TextField(verbose_name='Solução')
    severity = models.CharField(max_length=7, choices=SEVERITY_CHOICES, verbose_name='Gravidade')
    has_kaspersky = models.BooleanField(default=False, verbose_name='Está no catálogo da Kaspersky?')

    detected_at = models.DateField(verbose_name='Detectado em')
    created_at = models.DateField(auto_now_add=True, verbose_name='Criado em')
    updated_at = models.DateField(auto_now=True, verbose_name='Atualizado em')

    products = models.ManyToManyField(Software, verbose_name=Software._meta.verbose_name_plural)
    fixed = models.ManyToManyField(User, through='WhoFixed', verbose_name='Usuários')

    class Meta:
        verbose_name = 'Vulnerabilidade'

    def __str__(self):
        return self.name


class WhoFixed(models.Model):
    fixed_at = models.DateTimeField(auto_now_add=True, verbose_name='Corrigido em')

    user = models.ForeignKey(User, verbose_name=User._meta.verbose_name)
    vulnerability = models.ForeignKey(Vulnerability, verbose_name=Vulnerability._meta.verbose_name)

    class Meta:
        verbose_name = 'Quem corrigiu'

    def __str__(self):
        return self.user

hotsite/hotsite/core/views.py
from django.db.models import Count
from django.shortcuts import render

from hotsite.catalog.models import Vulnerability, Provider, Software, WhoFixed
from hotsite.posts.models import Post


def index(request):
    template_name = 'hotsite/index.html'
    title = 'Vulnerabilidades'

    if request.method == 'POST':
        if request.user.id:
            vulnerability_id = request.POST['vulnerability']

            instance = Vulnerability.objects.get(pk=int(vulnerability_id))
            WhoFixed(vulnerability=instance, user=request.user).save()

    instances = Vulnerability.objects.all()

    posts = Post.objects.all().order_by('-updated_at')[:8]

    # To check if user has fixed the vulnerability
    if request.user.id:
        for v in instances:
            if WhoFixed.objects.filter(user=request.user).filter(vulnerability=v).exists():
                fixed = True

            else:
                fixed = False

            v.whofixed = fixed

    context = {
        'title': title,
        'instances': instances,
        'posts': posts,
    }

    return render(request, template_name, context)


def catalog(request):
    template_name = 'hotsite/catalog.html'

    instances = Software.objects.all()

    context = {
        'head_title': 'Catálogo de Software',
        'title': 'Catálogo de Software',
        'instances': instances
    }

    return render(request, template_name, context)


def providers(request):
    template_name = 'hotsite/providers.html'
    title = 'Fornecedores'

    instances = Provider.objects.all()
    arr_providers = []

    for instance in instances:
        # TODO: Get the product with the most vulnerabilities registered and the last update

        provider = {
            'provider': instance,
            'products': Software.objects.filter(provider=instance),
        }

        arr_providers.append(provider)

    instances = arr_providers

    context = {
        'title': title,
        'instances': instances
    }

    return render(request, template_name, context)


def provider(request, pk):
    template_name = 'hotsite/provider.html'

    instance = Provider.objects.get(pk=pk)
    instances = Software.objects.filter(provider=instance).annotate(vulnerabilities=Count('vulnerability'))

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'instance': instance,
        'instances': instances
    }

    return render(request, template_name, context)


def products(request):
    template_name = 'hotsite/products.html'
    title = 'Produtos'

    instances = Software.objects.all().annotate(vulnerabilities=Count('vulnerability'))

    context = {
        'title': title,
        'instances': instances
    }

    return render(request, template_name, context)


def product(request, pk):
    template_name = 'hotsite/product.html'

    instance = Software.objects.get(pk=pk)
    instances = Vulnerability.objects.filter(products=instance)

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'instances': instances,
    }

    return render(request, template_name, context)


def vulnerability(request, pk):
    template_name = 'hotsite/vulnerability.html'

    instance = Vulnerability.objects.get(pk=pk)

    context = {
        'head_title': instance.name + ' | ',
        'title': instance.name,
        'instance': instance
    }

    return render(request, template_name, context)

hotsite/hotsite/panel/views.py
from django.contrib import messages
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from hotsite.catalog.models import Software, Provider, Vulnerability
from hotsite.core.decorators import login_required


def login(request):
    template_name = 'panel/login.html'

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)

                if user.is_staff:
                    return HttpResponseRedirect(reverse('panel:index'))
                else:
                    return HttpResponseRedirect(reverse('core:index'))

            else:
                messages.error(request, 'Conta inativa.')
        else:
            messages.error(request, 'Usuário ou senha incorretos.')

    return render(request, template_name)


def logout(request):
    auth_logout(request)

    return redirect('/panel/login')


@login_required
def index(request):
    template_name = 'panel/index.html'

    context = {
        'head_title': 'Painel',
        'softwares': Software.objects.all().count(),
        'providers': Provider.objects.all().count(),
        'vulnerabilities': Vulnerability.objects.all().count(),
    }

    return render(request, template_name, context)

hotsite/hotsite/core/templates/panel/add.html
{% extends 'panel/base.html' %}

{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap3-wysihtml5-npm/dist/bootstrap3-wysihtml5.min.css' %}" />
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>{{ title }}</strong>
                </div>

                <form method="POST">
                    <div class="card-block">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-dot-circle-o"></i> Enviar
                        </button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Limpar</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'bootstrap3-wysihtml5-npm/dist/bootstrap3-wysihtml5.min.js' %}"></script>
    <script src="{% static 'bootstrap3-wysihtml5-npm/dist/bootstrap3-wysihtml5.all.min.js' %}"></script>

    <script>
        $(function () {
            $('select').select2();
            $('#id_description').wysihtml5();
        });
    </script>
{% endblock %}

hotsite/hotsite/core/templates/panel/base.html
{% load static %}
<!--
 * CoreUI - Open Source Bootstrap Admin Template
 * @version v1.0.0-alpha.6
 * @link http://coreui.io
 * Copyright (c) 2017 creativeLabs Łukasz Holeczek
 * @license MIT
 -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
          content="{{ head_title }} — Portal de Vulnerabilidades | IFS — Instituto Federal de Sergipe">
    <meta name="author" content="Raphael Fontes - CTI Glória">
    <meta name="keyword"
          content="Bootstrap,Admin,Template,Open,Source,AngularJS,Angular,Angular2,Angular 2,Angular4,Angular 4,jQuery,CSS,HTML,RWD,Dashboard,React,React.js,Vue,Vue.js">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>{{ head_title }} - Portal de Vulnerabilidades | IFS - Instituto Federal de Sergipe</title>

    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

    <!-- Main styles for this application -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'toastr/build/toastr.min.css' %}">

    {% block custom_css %}{% endblock %}
</head>

<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>
    <ul class="nav navbar-nav ml-auto" style="margin-right: 10px;">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                <span class="d-md-down-none">{{ user.first_name }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url 'panel:logout' %}"><i class="fa fa-lock"></i> Sair</a>
            </div>
        </li>
    </ul>

</header>

<div class="app-body">
    <div class="sidebar">
        <nav class="sidebar-nav">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'panel:index' %}"><i class="fa fa-tachometer"></i> Painel</a>
                </li>
                <li class="nav-title">
                    Vulnerabilidades
                </li>
                <li class="nav-item open">
                    <a class="nav-link" href="{% url 'panel:catalog:vulnerabilities' %}"><i class="fa fa-bug"></i>
                        Catálogo
                    </a>
                </li>
                <li class="nav-title">
                    Catálogo de Software
                </li>
                <li class="nav-item open">
                    <a class="nav-link" href="{% url 'panel:catalog:providers' %}"><i class="fa fa-institution"></i>
                        Fornecedores
                    </a>
                </li>
                <li class="nav-item open">
                    <a class="nav-link" href="{% url 'panel:catalog:categories' %}"><i class="fa fa-bookmark"></i>
                        Categorias
                    </a>
                </li>
                <li class="nav-item open">
                    <a class="nav-link" href="{% url 'panel:catalog:licenses' %}"><i class="fa fa-check"></i>
                        Licenças
                    </a>
                </li>
                <li class="nav-item open">
                    <a class="nav-link" href="{% url 'panel:catalog:softwares' %}"><i class="fa fa-database"></i>
                        Softwares
                    </a>
                </li>
            </ul>
        </nav>
    </div>

    <!-- Main content -->
    <main class="main">

        <div class="container-fluid">

            <div class="animated fadeIn">
                {% block content %} {% endblock %}
            </div>

        </div>
        <!-- /.conainer-fluid -->
    </main>

</div>

<footer class="app-footer">
    <a href="http://www.ifs.edu.br">IFS - Instituto Federal de Sergipe</a>.
    <span class="float-right"><a href="http://gloria.ifs.edu.br">CTI - Glória</a>
        </span>
</footer>

<!-- Bootstrap and necessary plugins -->
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'tether/dist/js/tether.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'pace-js/pace.min.js' %}"></script>
<script src="{% static 'toastr/build/toastr.min.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>

<script>
    $(function () {
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    toastr.success('{{ message }}');
                {% else %}
                    toastr.error('{{ message }}');
                {% endif %}
            {% endfor %}
        {% endif %}
    });
</script>

{% block custom_js %} {% endblock %}

</body>

</html>

hotsite/hotsite/core/templates/panel/index.html
{% extends 'panel/base.html' %}

{% block content %}
    <div class="row">

        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-primary">
                <div class="card-body pb-0">
                    <h4 class="mb-0">{{ softwares }}</h4>
                    <p>Softwares</p>
                </div>
            </div>
        </div>
        <!--/.col-->

        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-primary">
                <div class="card-body pb-0">
                    <h4 class="mb-0">{{ providers }}</h4>
                    <p>Fornecedores</p>
                </div>
            </div>
        </div>
        <!--/.col-->

        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-primary">
                <div class="card-body pb-0">
                    <h4 class="mb-0">{{ vulnerabilities }}</h4>
                    <p>Vulnerabilidades</p>
                </div>
            </div>
        </div>
        <!--/.col-->

        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-primary">
                <div class="card-body pb-0">
                    <h4 class="mb-0">09/17</h4>
                    <p>Campus Atualizados</p>
                </div>
            </div>
        </div>
        <!--/.col-->

    </div>
    <!--/.row-->

{% endblock %}

hotsite/hotsite/core/templates/panel/list.html
{% extends 'panel/base.html' %}

{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span class="h4">{{ head_title }}</span>
                    <a href="{% url add_url %}" class="float-right" data-toggle="tooltip" title="Novo">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
                <div class="card-block">
                    <table id="data_table" class="table table-striped table-bordered" cellspacing="0"
                           width="100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Opção</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Opção</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for instance in instances %}
                            <tr>
                                <td>{{ instance.id }}</td>
                                <td>{{ instance.name }}</td>
                                <td>
                                    <a href="{% url edit_url instance.id %}" class="btn btn-sm btn-warning" data-toggle="tooltip" title="Editar">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>
    <script>
        $(function () {

            $('[data-toggle="tooltip"]').tooltip();

            $('#data_table').DataTable({
                paging: false,
                searching: true,
                language: {
                    processing: "Processando...",
                    search: "",
                    searchPlaceholder: "Procurar",
                    lengthMenu: "_MENU_ resultados por página",
                    info: "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    infoEmpty: "Mostrando 0 até 0 de 0 registros",
                    infoFiltered: "(Filtrados de _MAX_ registros)",
                    infoPostFix: "",
                    loadingRecords: "Carregando...",
                    zeroRecords: "Nenhum registro encontrado",
                    emptyTable: "Nenhum registro encontrado",
                    paginate: {
                        first: "Próximo",
                        previous: "Anterior",
                        next: "Próximo",
                        last: "Último"
                    },
                    aria: {
                        sortAscending: ": Ordenar colunas de forma ascendente",
                        sortDescending: ": Ordenar colunas de forma descendente"
                    }
                }
            });
            $('.dataTables_filter').addClass("text-right")
            $('.dataTables_filter input').addClass("form-control");
        });
    </script>
{% endblock %}

hotsite/hotsite/core/templates/panel/login.html
{% load static %}

<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Acesso - Portal de Vulnerabilidades | IFS - Instituto Federal de Sergipe</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'toastr/build/toastr.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="app flex-row align-items-center">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-group mb-0">
                <div class="card p-4">
                    <div class="card-body">
                        <img class="img-fluid" src="{% static 'img/logo.png' %}"/>
                        <hr/>
                        <h1>Acesso</h1>
                        <p class="text-muted">Preencha seus dados</p>

                        <form id="login-form" action="." method="POST" novalidate="">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <span class="input-group-addon">
                                    <i class="fa fa-user"></i>
                                </span>
                                <input type="text" class="form-control" placeholder="Usuário" name="username">
                            </div>
                            <div class="input-group mb-4">
                                <span class="input-group-addon">
                                    <i class="fa fa-lock"></i>
                                </span>
                                <input type="password" class="form-control" placeholder="Senha" name="password">
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-success px-4">Acessar</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>

                <div class="card text-white bg-success py-5 d-md-down-none" style="width:44%">
                    <div class="card-body text-center">
                        <div>
                            <h2>Dúvidas?</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie velit id
                                ipsum fermentum elementum. Orci varius natoque penatibus et magnis dis parturient
                                montes, nascetur ridiculus mus. Donec mauris tortor, posuere vestibulum magna euismod,
                                facilisis bibendum ligula. </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Bootstrap and necessary plugins -->

<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'tether/dist/js/tether.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'toastr/build/toastr.min.js' %}"></script>

<script>
    $(function () {

        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    toastr.success('{{ message }}');
                {% else %}
                    toastr.error('{{ message }}');
                {% endif %}
            {% endfor %}
        {% endif %}
    });
</script>

</body>

</html>