hotsite/hotsite/core/urls.py
from django.conf.urls import url

from hotsite.panel.views import login
from hotsite.posts.views import post, category
from .views import *

urlpatterns = [
    url('^$', index, name='index'),
    url('^login/$', login, name='login'),

    url('^catalog/$', catalog, name='catalog'),

    url('^vulnerability/(?P<pk>\w+)/$', vulnerability, name="vulnerability"),

    url('^providers/$', providers, name="providers"),
    url('^provider/(?P<pk>\w+)/$', provider, name="provider"),

    url('^products/$', products, name="products"),
    url('^product/(?P<pk>\w+)/$', product, name="product"),

    url('^category/(?P<category_slug>[\w-]+)/', category, name="category"),
    url('^article/(?P<category_slug>[\w-]+)/(?P<post_slug>[\w-]+)/', post, name="post"),
]

hotsite/hotsite/panel/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [

    url('^login/$', login, name='login'),
    url('^logout/$', logout, name='logout'),

    url('^catalog/', include('hotsite.catalog.urls', namespace='catalog')),

    url('^posts/', include('hotsite.posts.urls', namespace='posts')),

    url('^$', index, name='index'),
]

hotsite/hotsite/posts/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url('^categories/$', categories, name='categories'),
    url('^category/add/$', add_category, name='add_category'),
    url('^category/(?P<category_slug>[\w-]+)/$', category, name='category'),

    url('^posts/$', posts, name='posts'),
    url('^post/add/$', add_post, name='add_post'),
    url('^post/(?P<post_slug>[\w-]+)/$', post, name='post'),
]

hotsite/hotsite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url('^', include('hotsite.core.urls', namespace='core')),
    url('^panel/', include('hotsite.panel.urls', namespace='panel')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotsite/hotsite/catalog/views.py
from django.contrib import messages
from django.shortcuts import render

from .forms import *


def providers(request):
    template_name = 'panel/list.html'

    instances = Provider.objects.all()

    context = {
        'head_title': 'Fornecedores',
        'instances': instances,
        'add_url': 'panel:catalog:add_provider',
        'edit_url': 'panel:catalog:provider'
    }

    return render(request, template_name, context)


def add_provider(request):
    template_name = 'panel/add.html'

    form = ProviderForm(auto_id=False)

    if request.method == 'POST':
        form = ProviderForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Cadastrado com sucesso.')

    context = {
        'head_title': 'Novo Fornecedor',
        'title': 'Fornecedor',
        'form': form
    }

    return render(request, template_name, context)


def provider(request, pk):
    template_name = 'panel/add.html'

    instance = Provider.objects.get(pk=pk)

    form = ProviderForm(auto_id=False, instance=instance)

    if request.method == 'POST':
        form = ProviderForm(request.POST or None, instance=instance)

        if form.is_valid():
            form.save()

            messages.success(request, 'Atualizado com sucesso.')

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'form': form
    }

    return render(request, template_name, context)


def categories(request):
    template_name = 'panel/list.html'

    instances = Category.objects.all()

    context = {
        'head_title': 'Categorias',
        'instances': instances,
        'add_url': 'panel:catalog:add_category',
        'edit_url': 'panel:catalog:category'
    }

    return render(request, template_name, context)


def add_category(request):
    template_name = 'panel/add.html'

    form = CategoryForm(auto_id=False)

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Cadastrado com sucesso.')

    context = {
        'head_title': 'Nova Categoria',
        'title': 'Categoria',
        'form': form
    }

    return render(request, template_name, context)


def category(request, pk):
    template_name = 'panel/add.html'

    instance = Category.objects.get(pk=pk)

    form = CategoryForm(auto_id=False, instance=instance)

    if request.method == 'POST':
        form = CategoryForm(request.POST or None, instance=instance)

        if form.is_valid():
            form.save()

            messages.success(request, 'Atualizado com sucesso.')

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'form': form
    }

    return render(request, template_name, context)


def softwares(request):
    template_name = 'panel/list.html'

    instances = Software.objects.all()

    context = {
        'head_title': 'Softwares',
        'instances': instances,
        'add_url': 'panel:catalog:add_software',
        'edit_url': 'panel:catalog:software'
    }

    return render(request, template_name, context)


def add_software(request):
    template_name = 'panel/add.html'

    form = SoftwareForm(auto_id=False)

    if request.method == 'POST':
        form = SoftwareForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Cadastrado com sucesso.')

    context = {
        'head_title': 'Novo Software',
        'title': 'Software',
        'form': form
    }

    return render(request, template_name, context)


def software(request, pk):
    template_name = 'panel/add.html'

    instance = Software.objects.get(pk=pk)

    form = SoftwareForm(auto_id=False, instance=instance)

    if request.method == 'POST':
        form = SoftwareForm(request.POST or None, instance=instance)

        if form.is_valid():
            form.save()

            messages.success(request, 'Atualizado com sucesso.')

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'form': form
    }

    return render(request, template_name, context)


def vulnerabilities(request):
    template_name = 'panel/list.html'

    instances = Vulnerability.objects.all()

    context = {
        'head_title': 'Vulnerabilidades',
        'instances': instances,
        'add_url': 'panel:catalog:add_vulnerability',
        'edit_url': 'panel:catalog:vulnerability'
    }

    return render(request, template_name, context)


def add_vulnerability(request):
    template_name = 'panel/add.html'

    form = VulnerabilityForm(auto_id=False)

    if request.method == 'POST':
        list_products = request.POST.getlist('products')  # Get the products array and insert into a list

        request.POST._mutable = True  # For mutable the POST
        request.POST['products'] = list_products
        request.POST._mutable = False  # Return to no mutable

        form = VulnerabilityForm(request.POST)

        if form.is_valid():
            form.save()
            form = VulnerabilityForm(auto_id=False)

            messages.success(request, 'Cadastrado com sucesso.')

        else:
            pass

    context = {
        'head_title': 'Nova vulnerabilidade',
        'title': 'Vulnerabilidade',
        'form': form
    }

    return render(request, template_name, context)


def vulnerability(request, pk):
    template_name = 'panel/add.html'

    instance = Vulnerability.objects.get(pk=pk)

    if request.method == 'POST':
        list_products = request.POST.getlist('products')  # Get the products array and insert into a list

        request.POST._mutable = True  # For mutable the POST
        request.POST['products'] = list_products
        request.POST._mutable = False  # Return to no mutable

        form = VulnerabilityForm(request.POST, instance=instance)

        if form.is_valid():
            form.save()

            messages.success(request, 'Atualizado com sucesso.')

    form = VulnerabilityForm(instance=instance)

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'form': form
    }

    return render(request, template_name, context)


def licenses(request):
    template_name = 'panel/list.html'

    instances = License.objects.all()

    context = {
        'head_title': 'Licenças',
        'instances': instances,
        'add_url': 'panel:catalog:add_license',
        'edit_url': 'panel:catalog:license'
    }

    return render(request, template_name, context)


def add_license(request):
    template_name = 'panel/add.html'

    form = LicenseForm(auto_id=False)

    if request.method == 'POST':
        form = LicenseForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Cadastrado com sucesso.')

    context = {
        'head_title': 'Nova Licença',
        'title': 'Licença',
        'form': form
    }

    return render(request, template_name, context)


def license(request, pk):
    template_name = 'panel/add.html'

    instance = License.objects.get(pk=pk)

    form = LicenseForm(auto_id=False, instance=instance)

    if request.method == 'POST':
        form = LicenseForm(request.POST or None, instance=instance)

        if form.is_valid():
            form.save()

            messages.success(request, 'Atualizado com sucesso.')

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'form': form
    }

    return render(request, template_name, context)

hotsite/hotsite/core/views.py
from django.db.models import Count
from django.shortcuts import render

from hotsite.catalog.models import Vulnerability, Provider, Software, WhoFixed
from hotsite.posts.models import Post


def index(request):
    template_name = 'hotsite/index.html'
    title = 'Vulnerabilidades'

    if request.method == 'POST':
        if request.user.id:
            vulnerability_id = request.POST['vulnerability']

            instance = Vulnerability.objects.get(pk=int(vulnerability_id))
            WhoFixed(vulnerability=instance, user=request.user).save()

    instances = Vulnerability.objects.all()

    posts = Post.objects.all().order_by('-updated_at')[:8]

    # To check if user has fixed the vulnerability
    if request.user.id:
        for v in instances:
            if WhoFixed.objects.filter(user=request.user).filter(vulnerability=v).exists():
                fixed = True

            else:
                fixed = False

            v.whofixed = fixed

    context = {
        'title': title,
        'instances': instances,
        'posts': posts,
    }

    return render(request, template_name, context)


def catalog(request):
    template_name = 'hotsite/catalog.html'

    instances = Software.objects.all()

    context = {
        'head_title': 'Catálogo de Software',
        'title': 'Catálogo de Software',
        'instances': instances
    }

    return render(request, template_name, context)


def providers(request):
    template_name = 'hotsite/providers.html'
    title = 'Fornecedores'

    instances = Provider.objects.all()
    arr_providers = []

    for instance in instances:
        # TODO: Get the product with the most vulnerabilities registered and the last update

        provider = {
            'provider': instance,
            'products': Software.objects.filter(provider=instance),
        }

        arr_providers.append(provider)

    instances = arr_providers

    context = {
        'title': title,
        'instances': instances
    }

    return render(request, template_name, context)


def provider(request, pk):
    template_name = 'hotsite/provider.html'

    instance = Provider.objects.get(pk=pk)
    instances = Software.objects.filter(provider=instance).annotate(vulnerabilities=Count('vulnerability'))

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'instance': instance,
        'instances': instances
    }

    return render(request, template_name, context)


def products(request):
    template_name = 'hotsite/products.html'
    title = 'Produtos'

    instances = Software.objects.all().annotate(vulnerabilities=Count('vulnerability'))

    context = {
        'title': title,
        'instances': instances
    }

    return render(request, template_name, context)


def product(request, pk):
    template_name = 'hotsite/product.html'

    instance = Software.objects.get(pk=pk)
    instances = Vulnerability.objects.filter(products=instance)

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'instances': instances,
    }

    return render(request, template_name, context)


def vulnerability(request, pk):
    template_name = 'hotsite/vulnerability.html'

    instance = Vulnerability.objects.get(pk=pk)

    context = {
        'head_title': instance.name + ' | ',
        'title': instance.name,
        'instance': instance
    }

    return render(request, template_name, context)

hotsite/hotsite/panel/views.py
from django.contrib import messages
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from hotsite.catalog.models import Software, Provider, Vulnerability
from hotsite.core.decorators import login_required


def login(request):
    template_name = 'panel/login.html'

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)

                if user.is_staff:
                    return HttpResponseRedirect(reverse('panel:index'))
                else:
                    return HttpResponseRedirect(reverse('core:index'))

            else:
                messages.error(request, 'Conta inativa.')
        else:
            messages.error(request, 'Usuário ou senha incorretos.')

    return render(request, template_name)


def logout(request):
    auth_logout(request)

    return redirect('/panel/login')


@login_required
def index(request):
    template_name = 'panel/index.html'

    context = {
        'head_title': 'Painel',
        'softwares': Software.objects.all().count(),
        'providers': Provider.objects.all().count(),
        'vulnerabilities': Vulnerability.objects.all().count(),
    }

    return render(request, template_name, context)

hotsite/hotsite/posts/views.py
from django.contrib import messages
from django.shortcuts import render

from hotsite.posts.forms import *


def add_category(request):
    template_name = 'add.html'
    title = 'Nova categoria'

    form = CategoryForm(auto_id=False)

    if request.method == 'POST':
        form = CategoryForm(request.POST or None)

        if form.is_valid():
            form.save()
            title = form.instance.name

            messages.success(request, 'Cadastrado com sucesso!')

    context = {
        'head_title': title,
        'title': title,
        'form': form,
        'form_size': '8',

    }

    return render(request, template_name, context)


def category(request, category_slug):
    template_name = 'add.html'

    instance = Category.objects.get(slug=category_slug)
    form = CategoryForm(instance=instance)

    context = {
        'head_title': instance.name,
        'title': instance.name,
        'form': form,
        'form_size': '8',
    }

    return render(request, template_name, context)


def categories(request):
    template_name = 'list.html'

    instances = Category.objects.all()

    context = {
        'head_title': 'Categorias',
        'title': 'Categorias',
        'instances': instances,
        'add_url': 'panel:posts:add_category',
        'edit_url': 'panel:posts:category'
    }

    return render(request, template_name, context)


def posts(request):
    template_name = 'list_posts.html'

    instances = Post.objects.all()

    context = {
        'head_title': 'Post',
        'title': 'Post',
        'instances': instances,
        'add_url': 'panel:posts:add_post',
        'edit_url': 'panel:posts:post'
    }

    return render(request, template_name, context)


def add_post(request):
    template_name = 'add.html'
    title = 'Nova notícia'

    form = PostForm(auto_id=False)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)

        if form.is_valid():
            form.save()
            title = form.instance.title

            messages.success(request, 'Cadastrado com sucesso!')

        else:
            messages.error(request, 'Falha ao cadastrar.')

    context = {
        'head_title': title,
        'title': title,
        'form': form,
        'form_size': '8',
    }

    return render(request, template_name, context)


def post(request, post_slug):
    template_name = 'add.html'

    instance = Post.objects.get(slug=post_slug)
    form = PostForm(instance=instance)

    context = {
        'head_title': instance.title,
        'title': instance.title,
        'instance': instance,
        'form': form,
        'form_size': 8
    }

    return render(request, template_name, context)

hotsite/hotsite/core/templates/hotsite/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ head_title }} Vulnerabilidades — Instituto Federal de Sergipe</title>
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/hotsite.css' %}">
    <link rel="stylesheet" href="{% static 'css/posts.css' %}">
    {% block custom_css %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-md">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="http://www.ifs.edu.br">
        <img class="img-fluid" src="{% static 'img/logo.png' %}" width="250">
    </a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Vulnerabilidades</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:catalog' %}">Catálogo de Software</a>
            </li>
        </ul>
    </div>
    <div class="col-md-1">
        {% if user.id %}
            {{ user.first_name }}
            <a href="{% url 'panel:logout' %}" data-toggle="tooltip" data-placement="bottom" title="Sair">
                <i class="fa fa-sign-out"></i>
            </a>
        {% else %}
            <a href="{% url 'panel:login' %}">Login</a>
        {% endif %}
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="main-title">{{ title }}</h1>
            <div class="menu-content">
                <ul>
                    <li><a id="nav_all" href="{% url 'core:index' %}">Todos</a></li>
                    <li><a id="nav_provider" href="{% url 'core:providers' %}">Fornecedores</a></li>
                    <li><a id="nav_software" href="{% url 'core:products' %}">Produtos</a></li>
                    <div class="clear"></div>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer>
    <div class="container">
        <a href="http://www.ifs.edu.br">IFS - Instituto Federal de Sergipe</a>.
        <span class="float-right"><a href="http://gloria.ifs.edu.br">CTI - Glória</a>
        </span>
    </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

{% block custom_js %}{% endblock %}

</body>
</html>

hotsite/hotsite/core/templates/hotsite/catalog.html
{% extends 'hotsite/base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css">
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <table id="informations" class="table table-striped table-bordered" cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Fornecedor</th>
                                <th>Categoria</th>
                                <th>Versão Estável</th>
                                <th>Nº Processo Aquisição</th>
                                <th>Nº Licenças</th>
                                <th>Vigência</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Fornecedor</th>
                                <th>Categoria</th>
                                <th>Versão Estável</th>
                                <th>Nº Processo Aquisição</th>
                                <th>Nº Licenças</th>
                                <th>Vigência</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for instance in instances %}
                                <tr>
                                    <td>
                                        <a href="{% url 'core:product' instance.id %}">
                                            {{ instance }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'core:provider' instance.provider.id %}">
                                            {{ instance.provider.name }}
                                        </a>
                                    </td>
                                    <td>{{ instance.category }}</td>
                                    <td>{{ instace.version_stable }}</td>
                                    <td>{{ instance.process_number }}</td>
                                    <td>{{ instance.licenses_number }}</td>
                                    <td>{{ instance.license }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>

    <script>
        $(function () {

            $('#informations').DataTable({
                paging: false,
                searching: true,
                language: {
                    processing: "Processando...",
                    search: "",
                    searchPlaceholder: "Procurar",
                    lengthMenu: "_MENU_ resultados por página",
                    info: "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    infoEmpty: "Mostrando 0 até 0 de 0 registros",
                    infoFiltered: "(Filtrados de _MAX_ registros)",
                    infoPostFix: "",
                    loadingRecords: "Carregando...",
                    zeroRecords: "Nenhum registro encontrado",
                    emptyTable: "Nenhum registro encontrado",
                    paginate: {
                        first: "Próximo",
                        previous: "Anterior",
                        next: "Próximo",
                        last: "Último"
                    },
                    aria: {
                        sortAscending: ": Ordenar colunas de forma ascendente",
                        sortDescending: ": Ordenar colunas de forma descendente"
                    }
                }
            });
            $('#informations_filter input').addClass("form-control");
            $('#informations_filter input').addClass("mr-sm-2");
        });
    </script>
{% endblock %}

hotsite/hotsite/core/templates/hotsite/category.html
{% extends 'hotsite/base.html' %}
{% load filters %}

{% block content %}
    <div class="row posts">
        {% for instance in instances %}
            <div class="col-md-3">
                <div class="card">
                    <a href="{% url 'core:post' instance.category.slug instance.slug %}">
                        {% if instance.thumbnail %}
                            <img class="card-img-top img-fluid" src="{{ instance.thumbnail.url }}" alt="">
                        {% else %}
                            <img class="card-img-top img-fluid" src="http://via.placeholder.com/300x225" alt="">
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">{{ instance.title }}</h4>
                            <p class="card-text">{{ instance.content|excerpt:50 }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">{{ instance.updated_at }}</small>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block custom_js %}
    <script>
        $(function () {
            $('.menu-content').hide();
        });
    </script>
{% endblock %}

hotsite/hotsite/core/templates/hotsite/post.html
{% extends 'hotsite/base.html' %}

{% block content %}
    <div class="row justify-content-center about">
        <div class="col-md-2">
            EM <a href="{% url 'core:category' instance.category.slug %}">{{ instance.category|upper }}</a>
        </div>
        <div class="col-md-2">
            <i class="fa fa-clock-o" aria-hidden="true"></i> {{ instance.updated_at|date:'d M Y - H:i' }}
        </div>
    </div>

    <div class="parallax" style="background-image: url('{{ instance.thumbnail.url }}')"></div>

    <div class="row article">
        <div class="col-md-8">
            <p>{{ instance.content }}</p>
        </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script>
        $(function () {
            $('.menu-content').hide();
        });
    </script>
{% endblock %}

hotsite/hotsite/core/templates/hotsite/products.html
{% extends 'hotsite/base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css">
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <table id="informations" class="table table-striped table-bordered" cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Fornecedor</th>
                                <th>Vulnerabilidades</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Nome</th>
                                <th>Fornecedor</th>
                                <th>Vulnerabilidades</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for instance in instances %}
                                <tr>
                                    <td>
                                        <a href="{% url 'core:product' instance.id %}">
                                            {{ instance }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'core:provider' instance.provider.id %}">
                                            {{ instance.provider.name }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ instance.vulnerabilities }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>

    <script>
        $(function () {

            $('#informations').DataTable({
                paging: false,
                searching: true,
                language: {
                    processing: "Processando...",
                    search: "",
                    searchPlaceholder: "Procurar",
                    lengthMenu: "_MENU_ resultados por página",
                    info: "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    infoEmpty: "Mostrando 0 até 0 de 0 registros",
                    infoFiltered: "(Filtrados de _MAX_ registros)",
                    infoPostFix: "",
                    loadingRecords: "Carregando...",
                    zeroRecords: "Nenhum registro encontrado",
                    emptyTable: "Nenhum registro encontrado",
                    paginate: {
                        first: "Próximo",
                        previous: "Anterior",
                        next: "Próximo",
                        last: "Último"
                    },
                    aria: {
                        sortAscending: ": Ordenar colunas de forma ascendente",
                        sortDescending: ": Ordenar colunas de forma descendente"
                    }
                }
            });
            $('#informations_filter input').addClass("form-control");
            $('#informations_filter input').addClass("mr-sm-2");
        });
    </script>
{% endblock %}